### PR TITLE
GR11-HealthAndSecurityMonitoring-Issue

### LINKED ISSUE #406: GR11: Health and Security Monitoring Compliance status shows non compliant even though all the guardrails requirements are met
**Describe the bug**
Health and Security Monitoring Compliance status shows false even though all the guardrails requirements are met.

**To Reproduce**
1. Install v1.1.4 
2. Remediate the guardrail requirements
3. Observe status of Health Monitoring and Security Monitoring Items 

**Expected behavior**
Health and Security Monitoring update to compliant status once guardrail requirements are met. 

**Screenshots**
image

### PR DESCRIPTION
**Pull request by amrinderssc**
## Overview/Summary

fixes #406 
In GR11 Health and Security Monitoring was not showing compliant even when all remediation conditions were met

### CODE REVIEW

**Comment by mbrat2005** [comment]
@amrinderssc The security review asked us to use logic starting from a non-compliant state then change to compliant when we test the control. This way, if the test fails, we're not showing something to the falsely compliant. @josefehse reworked the logic on these modules to take this approach, but it sounds like we missed something...let me test and see if I can reproduce what you are seeing

**Comment by mbrat2005** [comment]
@amrinderssc I'm not able to reproduce a falsely reported non-compliant state. Can you check the Comments_s column in your last run--it should either contain a list of non compliant items or a compliant message

```kusto
GuardrailsCompliance_CL |
where ControlName_s startswith "GUARDRAIL 11" and ItemName_s in ( 'HealthMonitoring','SecurityMonitoring' ) |
project ControlName_s,ItemName_s,ComplianceStatus_b,Comments_s,ReportTime_s
```

image

**Comment by amrinderssc** [comment]
@mbrat2005 Output below: 

image

I have this reproduced in my environment if you would to take a peak inside please let me know

**Comment by josefehse** [comment]
I've reviewed and there was an issue with the detection logic. I've fixed and created a new PR. https://github.com/Azure/GuardrailsSolutionAccelerator/pull/416

**Comment by mbrat2005** [comment]
Closing, using #416 instead

**Pull request closed without merging**
